apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: mythical-beasts-data
  name: mythical-beasts-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
