---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mythical-server
  name: mythical-server
spec:
  ports:
  - name: "4000"
    port: 4000
    targetPort: 4000
  selector:
    name: mythical-server
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mythical-queue
  name: mythical-queue
spec:
  ports:
  - name: "4000"
    port: 5672
    targetPort: 5672
  selector:
    name: mythical-queue
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mythical-database
  name: mythical-database
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    name: mythical-database
status:
  loadBalancer: {}
