name: Terraform and Deploy

on:
  workflow_dispatch: # Manual trigger only

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Terraform code
        uses: actions/checkout@v2
        with:
          repository: suhailzap/terraform-grafana
          path: terraform-grafana  # Root directory
          ref: main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: terraform-mltp  # Your GCP project ID
          service_account_email: xxx@gmail.com  # Your service account email

      - name: Terraform Init
        working-directory: terraform-grafana  # Root directory
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform-grafana  # Root directory
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'  # Only apply on main branch
        working-directory: terraform-grafana  # Root directory
        run: terraform apply -auto-approve

  deploy:
    runs-on: ubuntu-latest
    needs: terraform
    if: github.ref == 'refs/heads/main'  # Only deploy on main branch after Terraform applies
    steps:
      - name: Checkout Compose file
        uses: actions/checkout@v2
        with:
          repository: suhailzap/terraform-grafana
          path: terraform-grafana  # Root directory
          ref: main

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: terraform-mltp  # Your GCP project ID
          service_account_email: xxx@gmail.com  # Your service account email

      - name: Install Docker and Docker Compose on GCP Instance
        run: |
          INSTANCE_NAME="grafana-instance"
          ZONE="me-central1-a"
          gcloud compute scp terraform-grafana/install_docker.py $INSTANCE_NAME:~ --zone=$ZONE
          gcloud compute ssh $INSTANCE_NAME --zone=$ZONE -- 'python3 install_docker.py'

      - name: Deploy Grafana on GCP Instance
        run: |
          INSTANCE_NAME="grafana-instance"
          ZONE="me-central1-a"
          gcloud compute scp --recurse terraform-grafana/intro-to-mltp-main $INSTANCE_NAME:~/ --zone=$ZONE
          gcloud compute ssh $INSTANCE_NAME --zone=$ZONE -- 'cd ~/intro-to-mltp-main && sudo docker-compose up -d'

      - name: Get GCP Instance Public IP Address
        id: get_ip
        run: |
          INSTANCE_NAME="grafana-instance"
          ZONE="me-central1-a"
          IP=$(gcloud compute instances describe $INSTANCE_NAME --format='get(networkInterfaces[0].accessConfigs[0].natIP)' --zone=$ZONE)
          echo "Public IP Address: $IP"
